name: Build, publish, cleanup

on:
  push:
    branches:
      - "main"

jobs:
  build-publish-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          sbom: false
          platforms: linux/amd64
          no-cache: true
          pull: true
          push: true
          tags: ghcr.io/berkaycagir/hls-restream:latest
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.PAT }}
          container: hls-restream
          dry-run: false
          prune-untagged: true
